add test script for header files in non-eslinted js source files

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -97,6 +97,31 @@ jobs:
           name: fix eslint cache
           command: yarn lerna exec ../../build_utils/fix_eslint_cache.sh
 
+      - run:
+          # eslint will verify that the license header exists on the linted source files, this step is
+          # to verify that other non-linted files also contains the license header (and therefore this is
+          # in the 'build' job)
+          name: verify that the license header is prepend to the non eslint'd source files
+          command: |
+            # get the license header from the eslintrc configuration
+            set -e
+            if [ ! -f 'eslintrc' ]; then
+              echo 'cannot find eslintrc file'
+              exit 1
+            fi
+            license_header=$(node -e "var license_head = require('./eslintrc'); console.log(\`/*\${license_head.rules['header/header'][2].join('\n')}*/\`)")
+            src_files_without_license_header=""
+            for f in $(find . -type f -name '*.js' -not -path '*node_modules*' -not -path '*dist\/*' ); do
+              if grep -q "$license_header" "$f"; then
+                src_files_without_license_header+="$f\n"
+              fi
+            done
+
+            if [ ! -z "$src_files_without_license_header" ]; then
+              echo -e "the following source files do not contain license header:\n${src_files_without_license_header}"
+              exit 1
+            fi
+
       - run: yarn build
 
       - run:
